import type { Metadata } from "next";
import vazirFont from "@/constants/localfont";
import Header from "@/components/common/header/header";
import "@/styles/globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html data-theme="emerald" lang="fa" dir="rtl">
            <body className={`${vazirFont.variable} font-sans`}>
                <Header />
                {children}
            </body>
        </html>
    );
}
