import Content from '@/components/home/content/content';
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        absolute: 'خانه'
    },
    description: "Generated by create next app",
};

export default function Home() {
    return <Content />
}
